parameters:
  codein.fieldtype.color.identifier: 'codeincolor'

services:
  Codein\eZColorPicker\FieldType\ColorPicker\Type:
    autoconfigure: false
    autowire: true
    public: true
    calls:
      - [ 'setColorConverter', ["@Codein\\ColorConverter\\ColorConverter"] ]
    tags:
      - { name: ibexa.field_type, alias: "%codein.fieldtype.color.identifier%" }
      - { name: ibexa.admin_ui.field_type.form.mapper.value, fieldType: "%codein.fieldtype.color.identifier%" }
      - { name: ibexa.admin_ui.field_type.form.mapper.definition, fieldType: "%codein.fieldtype.color.identifier%" }

  codein.ezcolorpicker.fieldtype.colorpicker.type.notindexable:
    class: Ibexa\Core\FieldType\Unindexed
    tags:
      - { name: ibexa.field_type.indexable, alias: "%codein.fieldtype.color.identifier%" }

